version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh /etc/init.d/mysql start
    entrypoint: ./entrypoint.sh
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    volumes:
      - uploadartefatos:/app/uploadartefatos
volumes:
  mysql_data:
  uploadartefatos:
