version: "3"

services:
  db: 
    image: mysql:5.6
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: infodoc@adm
        MYSQL_DATABASE: infodoc_open
        MYSQL_USER: infodoc
        MYSQL_PASSWORD: infodoc@adm
    ports:
        - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #command: ruby /script/server -d
    entrypoint: ./entrypoint.sh
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    depends_on: 
      - db
    links:
      - db
    environment:
      DB_USER: infodoc
      DB_NAME: infodoc_open
      DB_PASSWORD: infodoc@adm
      DB_HOST: db
volumes:
  mysql_data:
